# Generated by Django 3.2.8 on 2021-10-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('dataset_name', models.CharField(max_length=255)),
                ('column_name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='SetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_control.datasets')),
            ],
        ),
        migrations.CreateModel(
            name='DataValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_control.datasets')),
            ],
        ),
    ]
