# Generated by Django 3.2.8 on 2021-10-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasets',
            name='column_name',
        ),
        migrations.CreateModel(
            name='ColumnNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=63)),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_control.datasets')),
            ],
        ),
    ]
